services:
  db:
    build:
      context: images
      dockerfile: pg.Dockerfile
    image: custom_postgres
    ports:
      - "54321:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secrets
      - PGUSER=postgres # so, `psql` alone works inside container, instead of `psql -U postgres`
    volumes:
      - ./downloads:/downloads
      - ./initdb:/docker-entrypoint-initdb.d/
      - database:/var/lib/postgresql/data
  adminer:
    image: adminer
    depends_on:
      - db
    environment:
      - ADMINER_DEFAULT_SERVER=db
    ports:
      - "8080:8080"

volumes:
  database:
